apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-banking-secrets
  namespace: banking
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
    keyvaultName: "REPLACE_WITH_KEYVAULT_NAME"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: banking-sql-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: banking-jwt-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: banking-appinsights-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: "REPLACE_WITH_TENANT_ID"
  secretObjects:
  - secretName: banking-secrets
    type: Opaque
    data:
    - objectName: banking-sql-connection-string
      key: connection-string
    - objectName: banking-jwt-key
      key: jwt-key
    - objectName: banking-appinsights-connection-string
      key: appinsights-connection-string
